import type { CurriculumSeed } from './types'

export const previewSeed: CurriculumSeed = {
  modules: [
    {
      id: 'module-aspnet-core',
      slug: 'aspnet-core',
      title: 'ASP.NET Core API Engineering',
      description: 'HTTP APIs, contracts, diagnostics, validation, and production behavior.',
      order: 1,
      topics: [
        {
          id: 'topic-minimal-api-routing',
          slug: 'minimal-api-routing',
          title: 'Minimal API route groups',
          summary: 'Design stable route groups with typed results and cancellation-aware handlers.',
          order: 1,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-problem-details',
          slug: 'problem-details',
          title: 'ProblemDetails error contracts',
          summary: 'Return consistent validation and failure responses from API boundaries.',
          order: 2,
          taskTypes: ['read', 'review', 'writeTests'],
        },
        {
          id: 'topic-openapi-contracts',
          slug: 'openapi-contracts',
          title: 'OpenAPI as frontend contract',
          summary: 'Treat the generated contract as the agreement between API and TypeScript client.',
          order: 3,
          taskTypes: ['read', 'build', 'document'],
        },
        {
          id: 'topic-aspnet-middleware-pipeline',
          slug: 'aspnet-middleware-pipeline',
          title: 'ASP.NET Core middleware pipeline',
          summary: 'Understand middleware ordering, short-circuiting, endpoint routing, exception handling, and request/response flow.',
          order: 4,
          taskTypes: ['read', 'watch', 'build', 'debug'],
        },
        {
          id: 'topic-aspnet-dependency-injection-options',
          slug: 'aspnet-dependency-injection-options',
          title: 'Dependency injection and Options pattern',
          summary: 'Use scoped services, typed options, validation, and lifetime boundaries without leaking infrastructure into handlers.',
          order: 5,
          taskTypes: ['read', 'build', 'review'],
        },
        {
          id: 'topic-aspnet-validation-filters',
          slug: 'aspnet-validation-filters',
          title: 'Validation and endpoint filters',
          summary: 'Apply request validation, endpoint filters, and ProblemDetails responses at API boundaries.',
          order: 6,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-aspnet-observability',
          slug: 'aspnet-observability',
          title: 'ASP.NET Core observability',
          summary: 'Connect structured logging, metrics, tracing, health checks, and diagnostics to production API behavior.',
          order: 7,
          taskTypes: ['read', 'watch', 'debug', 'review'],
        },
      ],
    },
    {
      id: 'module-ef-core',
      slug: 'ef-core',
      title: 'EF Core Persistence',
      description: 'SQLite-backed persistence, projections, migrations, and re-import safety.',
      order: 2,
      topics: [
        {
          id: 'topic-sqlite-modeling',
          slug: 'sqlite-modeling',
          title: 'SQLite model configuration',
          summary: 'Map aggregate data explicitly with keys, indexes, owned state, and conversions.',
          order: 1,
          taskTypes: ['read', 'build', 'review'],
        },
        {
          id: 'topic-idempotent-importer',
          slug: 'idempotent-importer',
          title: 'Idempotent curriculum import',
          summary: 'Upsert reference data while preserving progress and linked study records.',
          order: 2,
          taskTypes: ['build', 'debug', 'writeTests'],
        },
        {
          id: 'topic-ef-query-projections',
          slug: 'ef-query-projections',
          title: 'EF Core query projection and tracking',
          summary: 'Shape read models with Select, avoid over-fetching, choose tracking/no-tracking deliberately, and keep filtering in SQL.',
          order: 3,
          taskTypes: ['read', 'build', 'review'],
        },
        {
          id: 'topic-ef-concurrency',
          slug: 'ef-concurrency',
          title: 'EF Core optimistic concurrency',
          summary: 'Use concurrency tokens, conflict handling, retries, and user-safe merge behavior for production data updates.',
          order: 4,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-ef-migrations-production',
          slug: 'ef-migrations-production',
          title: 'EF Core migrations for production',
          summary: 'Review generated migrations, avoid accidental data loss, script schema rollout, and reason about SQLite constraints.',
          order: 5,
          taskTypes: ['read', 'review', 'document'],
        },
      ],
    },
    {
      id: 'module-dotnet-bcl',
      slug: 'dotnet-bcl',
      title: '.NET & BCL',
      description: 'Core .NET APIs and runtime behavior: collections, text, IO, async, memory, diagnostics, serialization, and time.',
      order: 3,
      topics: [
        {
          id: 'topic-bcl-collections',
          slug: 'bcl-collections',
          title: 'BCL collections and equality',
          summary: 'Use List, Dictionary, HashSet, immutable/read-only collections, comparers, equality, ordering, and allocation tradeoffs.',
          order: 1,
          taskTypes: ['read', 'build', 'debug'],
        },
        {
          id: 'topic-bcl-linq',
          slug: 'bcl-linq',
          title: 'LINQ operators and deferred execution',
          summary: 'Understand IEnumerable, IQueryable boundaries, deferred execution, materialization, grouping, joins, and accidental repeated enumeration.',
          order: 2,
          taskTypes: ['read', 'build', 'review'],
        },
        {
          id: 'topic-bcl-strings-globalization',
          slug: 'bcl-strings-globalization',
          title: 'Strings, formatting, and globalization',
          summary: 'Handle string comparison, interpolation, parsing, spans, culture-aware formatting, ordinal rules, and Unicode edge cases.',
          order: 3,
          taskTypes: ['read', 'debug', 'writeTests'],
        },
        {
          id: 'topic-bcl-datetime-time',
          slug: 'bcl-datetime-time',
          title: 'DateTime, DateOnly, TimeOnly, and TimeProvider',
          summary: 'Model time correctly with UTC, offsets, clocks, deterministic tests, scheduling boundaries, and date-only domain values.',
          order: 4,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-bcl-async-tasks',
          slug: 'bcl-async-tasks',
          title: 'Tasks, async, and cancellation',
          summary: 'Use Task, ValueTask, async/await, cancellation tokens, timeouts, exception flow, and concurrency without blocking threads.',
          order: 5,
          taskTypes: ['read', 'watch', 'build', 'debug'],
        },
        {
          id: 'topic-bcl-streams-files',
          slug: 'bcl-streams-files',
          title: 'Streams, files, and pipelines',
          summary: 'Work with Stream, File, Path, buffers, async IO, pipelines, backpressure, and safe local file processing.',
          order: 6,
          taskTypes: ['read', 'build', 'debug'],
        },
        {
          id: 'topic-bcl-memory-span',
          slug: 'bcl-memory-span',
          title: 'Memory, Span<T>, and allocation control',
          summary: 'Use Span, Memory, ArrayPool, slicing, stack allocation, and benchmarking to reduce allocations without unsafe complexity.',
          order: 7,
          taskTypes: ['read', 'watch', 'build', 'review'],
        },
        {
          id: 'topic-bcl-system-text-json',
          slug: 'bcl-system-text-json',
          title: 'System.Text.Json contracts',
          summary: 'Design JSON serialization with naming policies, converters, required members, polymorphism, source generation, and versioning.',
          order: 8,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-bcl-diagnostics-logging',
          slug: 'bcl-diagnostics-logging',
          title: 'Diagnostics, logging, and Activity',
          summary: 'Use ILogger, Activity, meters, counters, EventSource, and diagnostic boundaries to understand production behavior.',
          order: 9,
          taskTypes: ['read', 'debug', 'review'],
        },
        {
          id: 'topic-bcl-cryptography',
          slug: 'bcl-cryptography',
          title: 'Cryptography and secure randomness',
          summary: 'Use RandomNumberGenerator, hashing, HMAC, password-safe primitives, and avoid homegrown crypto mistakes.',
          order: 10,
          taskTypes: ['read', 'review', 'writeTests'],
        },
      ],
    },
    {
      id: 'module-js-node-standard-library',
      slug: 'js-node-standard-library',
      title: 'JavaScript & Node.js Standard Library',
      description: 'JavaScript built-ins and Node core APIs: language runtime, collections, modules, streams, filesystem, HTTP, crypto, and diagnostics.',
      order: 4,
      topics: [
        {
          id: 'topic-js-values-equality',
          slug: 'js-values-equality',
          title: 'JavaScript values, equality, and coercion',
          summary: 'Understand primitives, objects, truthiness, Object.is, ===, nullish coalescing, optional chaining, and coercion traps.',
          order: 1,
          taskTypes: ['read', 'debug', 'writeTests'],
        },
        {
          id: 'topic-js-arrays-iterables',
          slug: 'js-arrays-iterables',
          title: 'Arrays, iterables, Map, and Set',
          summary: 'Use arrays, iterators, generators, Map, Set, WeakMap, sorting, grouping, and immutable update patterns correctly.',
          order: 2,
          taskTypes: ['read', 'build', 'debug'],
        },
        {
          id: 'topic-js-promises-event-loop',
          slug: 'js-promises-event-loop',
          title: 'Promises, event loop, and scheduling',
          summary: 'Understand Promise jobs, microtasks, macrotasks, async/await, timers, AbortController, and rendering or server scheduling effects.',
          order: 3,
          taskTypes: ['read', 'watch', 'build', 'debug'],
        },
        {
          id: 'topic-js-modules-packages',
          slug: 'js-modules-packages',
          title: 'ES modules and package resolution',
          summary: 'Use import/export, package exports, CommonJS interop, module resolution, tree-shaking boundaries, and build/runtime differences.',
          order: 4,
          taskTypes: ['read', 'build', 'debug'],
        },
        {
          id: 'topic-node-fs-path',
          slug: 'node-fs-path',
          title: 'Node fs, path, and URL',
          summary: 'Use fs/promises, streams, Path, URL, file URLs, atomic writes, permissions, and cross-platform path handling.',
          order: 5,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-node-streams-buffers',
          slug: 'node-streams-buffers',
          title: 'Node streams, Buffer, and backpressure',
          summary: 'Handle readable/writable streams, pipeline, Transform, Buffer encoding, backpressure, and large-file processing.',
          order: 6,
          taskTypes: ['read', 'watch', 'build', 'debug'],
        },
        {
          id: 'topic-node-http-fetch',
          slug: 'node-http-fetch',
          title: 'Node HTTP, fetch, and Web APIs',
          summary: 'Use fetch, Request, Response, headers, AbortSignal, HTTP agents, timeouts, retries, and server/client API boundaries.',
          order: 7,
          taskTypes: ['read', 'build', 'debug'],
        },
        {
          id: 'topic-node-crypto',
          slug: 'node-crypto',
          title: 'Node crypto and secure tokens',
          summary: 'Use crypto randomUUID, randomBytes, hashes, HMAC, subtle crypto boundaries, and avoid insecure token generation.',
          order: 8,
          taskTypes: ['read', 'review', 'writeTests'],
        },
        {
          id: 'topic-node-child-process-worker',
          slug: 'node-child-process-worker',
          title: 'child_process and worker_threads',
          summary: 'Run external processes and CPU-bound work with spawn, execFile, workers, message passing, cancellation, and output limits.',
          order: 9,
          taskTypes: ['read', 'build', 'debug'],
        },
        {
          id: 'topic-node-diagnostics',
          slug: 'node-diagnostics',
          title: 'Node diagnostics and performance',
          summary: 'Use console, performance, async hooks, inspector, process reports, memory snapshots, and event-loop delay measurements.',
          order: 10,
          taskTypes: ['read', 'debug', 'review'],
        },
      ],
    },
    {
      id: 'module-react-typescript',
      slug: 'react-typescript',
      title: 'React + TypeScript Learning UI',
      description: 'Dense, code-adjacent learning workflows with server state kept explicit.',
      order: 5,
      topics: [
        {
          id: 'topic-tanstack-query',
          slug: 'tanstack-query',
          title: 'TanStack Query catalog state',
          summary: 'Cache server-owned catalog/progress data without hiding API behavior.',
          order: 1,
          taskTypes: ['read', 'build'],
        },
        {
          id: 'topic-tailwind-product-ui',
          slug: 'tailwind-product-ui',
          title: 'Tailwind product interface',
          summary: 'Build restrained dark product screens without generic dashboard ornament.',
          order: 2,
          taskTypes: ['build', 'review', 'document'],
        },
        {
          id: 'topic-typescript-type-modeling',
          slug: 'typescript-type-modeling',
          title: 'TypeScript domain type modeling',
          summary: 'Use unions, generics, mapped types, discriminated states, branded IDs, and API DTO boundaries without type gymnastics.',
          order: 3,
          taskTypes: ['read', 'build', 'review'],
        },
        {
          id: 'topic-typescript-runtime-validation',
          slug: 'typescript-runtime-validation',
          title: 'TypeScript runtime validation boundary',
          summary: 'Separate compile-time types from runtime validation, API parsing, narrowing, error display, and unsafe external data.',
          order: 4,
          taskTypes: ['read', 'build', 'writeTests'],
        },
        {
          id: 'topic-react-state-composition',
          slug: 'react-state-composition',
          title: 'React state and component composition',
          summary: 'Design state ownership, derived state, controlled inputs, effects, memoization, and component boundaries for learning workflows.',
          order: 5,
          taskTypes: ['read', 'build', 'review'],
        },
        {
          id: 'topic-react-accessibility-forms',
          slug: 'react-accessibility-forms',
          title: 'React forms and accessibility',
          summary: 'Build keyboard-friendly forms with labels, validation messages, focus management, ARIA only when needed, and predictable submit flow.',
          order: 6,
          taskTypes: ['read', 'build', 'review'],
        },
      ],
    },
  ],
  phases: [
    {
      id: 'phase-foundation',
      slug: 'foundation-path',
      title: 'Foundation Path',
      description: 'API, persistence, and frontend contract fundamentals.',
      order: 1,
      topics: [
        { topicId: 'topic-minimal-api-routing', order: 1 },
        { topicId: 'topic-sqlite-modeling', order: 2 },
        { topicId: 'topic-bcl-collections', order: 3 },
        { topicId: 'topic-js-values-equality', order: 4 },
        { topicId: 'topic-tanstack-query', order: 5 },
      ],
    },
    {
      id: 'phase-runtime-foundations',
      slug: 'runtime-foundations',
      title: 'Runtime and Standard Library Foundations',
      description: 'BCL, JavaScript, and Node APIs that support real production full-stack work.',
      order: 2,
      topics: [
        { topicId: 'topic-bcl-linq', order: 1 },
        { topicId: 'topic-bcl-async-tasks', order: 2 },
        { topicId: 'topic-bcl-streams-files', order: 3 },
        { topicId: 'topic-bcl-system-text-json', order: 4 },
        { topicId: 'topic-js-promises-event-loop', order: 5 },
        { topicId: 'topic-node-fs-path', order: 6 },
        { topicId: 'topic-node-streams-buffers', order: 7 },
        { topicId: 'topic-node-http-fetch', order: 8 },
      ],
    },
  ],
}
