// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFSSPlatform.Infrastructure.Persistence;

#nullable disable

namespace SFSSPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudyPlatformDbContext))]
    [Migration("20260630113555_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.CurriculumModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.PhaseTopic", b =>
                {
                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhaseId", "TopicId");

                    b.HasIndex("TopicId");

                    b.HasIndex("PhaseId", "Order");

                    b.ToTable("PhaseTopics", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ModuleId", "Order");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.TopicTaskType", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId", "TaskType");

                    b.ToTable("TopicTaskTypes", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.PhaseTopic", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.Curriculum.Phase", "Phase")
                        .WithMany("Topics")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFSSPlatform.Domain.Curriculum.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Topic", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.Curriculum.CurriculumModule", "Module")
                        .WithMany("Topics")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SFSSPlatform.Domain.Curriculum.TopicProgress", "Progress", b1 =>
                        {
                            b1.Property<int>("TopicId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressCompletedAt");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressStartedAt");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressStatus");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressUpdatedAt");

                            b1.HasKey("TopicId");

                            b1.ToTable("Topics");

                            b1.WithOwner()
                                .HasForeignKey("TopicId");
                        });

                    b.Navigation("Module");

                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.TopicTaskType", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.Curriculum.Topic", "Topic")
                        .WithMany("TaskTypes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.CurriculumModule", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Phase", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Topic", b =>
                {
                    b.Navigation("TaskTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
