// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFSSPlatform.Infrastructure.Persistence;

#nullable disable

namespace SFSSPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudyPlatformDbContext))]
    [Migration("20260630202759_AddTopicResourceLinks")]
    partial class AddTopicResourceLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.CurriculumModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.PhaseTopic", b =>
                {
                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhaseId", "TopicId");

                    b.HasIndex("TopicId");

                    b.HasIndex("PhaseId", "Order");

                    b.ToTable("PhaseTopics", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ModuleId", "Order");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.TopicTaskType", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId", "TaskType");

                    b.ToTable("TopicTaskTypes", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.LearningResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbedUrl")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceDocumentChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchProgressSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsWatched");

                    b.HasIndex("SourceDocumentChunkId");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("Tags");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("LearningResources", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.SourceDocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceMaterialId", "Order")
                        .IsUnique();

                    b.HasIndex("SourceMaterialId", "StartPage");

                    b.ToTable("SourceDocumentChunks", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.SourceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractionError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.HasIndex("StableKey")
                        .IsUnique();

                    b.ToTable("SourceMaterials", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.StudyAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyItemId", "AttemptedAt");

                    b.ToTable("StudyAttempts", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.StudyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceDocumentChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceExcerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("Status");

                    b.HasIndex("SourceDocumentChunkId", "Kind");

                    b.HasIndex("Status", "NextReviewAt", "Id");

                    b.ToTable("StudyItems", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.TopicResourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearningResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoCandidateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LearningResourceId");

                    b.HasIndex("TopicId");

                    b.HasIndex("VideoCandidateId");

                    b.HasIndex("TopicId", "LearningResourceId")
                        .IsUnique();

                    b.HasIndex("TopicId", "VideoCandidateId")
                        .IsUnique();

                    b.ToTable("TopicResourceLinks", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.TrustedYouTubeChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("Tags");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("TrustedYouTubeChannels", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.VideoCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelUrl")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbedUrl")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LearningResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName");

                    b.HasIndex("Difficulty");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("LearningResourceId");

                    b.HasIndex("Status");

                    b.HasIndex("Tags");

                    b.ToTable("VideoCandidates", (string)null);
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.PhaseTopic", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.Curriculum.Phase", "Phase")
                        .WithMany("Topics")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFSSPlatform.Domain.Curriculum.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Topic", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.Curriculum.CurriculumModule", "Module")
                        .WithMany("Topics")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SFSSPlatform.Domain.Curriculum.TopicProgress", "Progress", b1 =>
                        {
                            b1.Property<int>("TopicId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressCompletedAt");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressStartedAt");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressStatus");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProgressUpdatedAt");

                            b1.HasKey("TopicId");

                            b1.ToTable("Topics");

                            b1.WithOwner()
                                .HasForeignKey("TopicId");
                        });

                    b.Navigation("Module");

                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.TopicTaskType", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.Curriculum.Topic", "Topic")
                        .WithMany("TaskTypes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.LearningResource", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.StudyContent.SourceDocumentChunk", "SourceDocumentChunk")
                        .WithMany()
                        .HasForeignKey("SourceDocumentChunkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SFSSPlatform.Domain.StudyContent.SourceMaterial", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceDocumentChunk");

                    b.Navigation("SourceMaterial");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.SourceDocumentChunk", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.StudyContent.SourceMaterial", "SourceMaterial")
                        .WithMany("Chunks")
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMaterial");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.StudyAttempt", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.StudyContent.StudyItem", "StudyItem")
                        .WithMany()
                        .HasForeignKey("StudyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyItem");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.StudyItem", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.StudyContent.SourceDocumentChunk", "SourceDocumentChunk")
                        .WithMany()
                        .HasForeignKey("SourceDocumentChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFSSPlatform.Domain.StudyContent.SourceMaterial", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceDocumentChunk");

                    b.Navigation("SourceMaterial");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.TopicResourceLink", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.StudyContent.LearningResource", "LearningResource")
                        .WithMany()
                        .HasForeignKey("LearningResourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SFSSPlatform.Domain.Curriculum.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFSSPlatform.Domain.StudyContent.VideoCandidate", "VideoCandidate")
                        .WithMany()
                        .HasForeignKey("VideoCandidateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LearningResource");

                    b.Navigation("Topic");

                    b.Navigation("VideoCandidate");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.VideoCandidate", b =>
                {
                    b.HasOne("SFSSPlatform.Domain.StudyContent.LearningResource", "LearningResource")
                        .WithMany()
                        .HasForeignKey("LearningResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LearningResource");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.CurriculumModule", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Phase", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.Curriculum.Topic", b =>
                {
                    b.Navigation("TaskTypes");
                });

            modelBuilder.Entity("SFSSPlatform.Domain.StudyContent.SourceMaterial", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
